version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bankdb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - bank-network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: bankdb
      DB_PORT: "5432"
      JWT_SECRET: your_secret_key
    networks:
      - bank-network

volumes:
  db-data:

networks:
  bank-network:
