name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./... -cover

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Backend Docker Image
        run: |
          docker build -t bankapp-backend:latest -f dockerfile.backend .
          docker save bankapp-backend:latest > backend-docker-image.tar

      - name: Build Frontend Docker Image
        run: |
          docker build -t bankapp-frontend:latest -f dockerfile.frontend .
          docker save bankapp-frontend:latest > frontend-docker-image.tar

      - name: Upload Docker Image Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: |
            backend-docker-image.tar
            frontend-docker-image.tar

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Docker Image Artifacts
        uses: actions/download-artifact@v3
        with:
          name: docker-images

      - name: Load Backend Docker Image
        run: docker load < backend-docker-image.tar

      - name: Load Frontend Docker Image
        run: docker load < frontend-docker-image.tar

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and Push Backend Docker Image
        run: |
          docker tag bankapp-backend:latest "${{ secrets.DOCKER_USERNAME }}/bankapp-backend:latest"
          docker push "${{ secrets.DOCKER_USERNAME }}/bankapp-backend:latest"

      - name: Tag and Push Frontend Docker Image
        run: |
          docker tag bankapp-frontend:latest "${{ secrets.DOCKER_USERNAME }}/bankapp-frontend:latest"
          docker push "${{ secrets.DOCKER_USERNAME }}/bankapp-frontend:latest"

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: deploy

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'

      - name: Install dependencies
        run: go mod tidy

      - name: Run integration tests
        env:
          DATABASE_URL: postgres://test:test@localhost:5432/test_db?sslmode=disable
        run: go test -v ./test/integration -cover
