name: CI/CD Pipeline with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test with Docker Compose
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонировать репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Шаг 3: Запуск Docker Compose и выполнение тестов
      - name: Build and Run Tests
        run: |
          docker-compose -f docker-compose.yml up --build --abort-on-container-exit --exit-code-from app

      # Шаг 4: Чистка
      - name: Cleanup Docker
        if: always()
        run: docker-compose -f docker-compose.yml down

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: [build-and-test]

    steps:
      # Шаг 1: Клонировать репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Логин в Docker Hub
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Шаг 3: Публикация Docker Compose в Docker Hub
      - name: Push Docker Image
        run: |
          docker-compose -f docker-compose.yml build app
          docker tag bankapp_app:latest $DOCKER_USERNAME/bankapp:latest
          docker push $DOCKER_USERNAME/bankapp:latest
