name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 4: Run tests
      - name: Run tests
        run: go test -v ./...

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: docker build -f ./Dockerfile -t bankapp:latest .

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Tag and Push Docker Image
      - name: Tag and Push Docker Image
        run: |
          docker tag bankapp:latest "${{ secrets.DOCKER_USERNAME }}/bankapp:latest"
          docker push "${{ secrets.DOCKER_USERNAME }}/bankapp:latest"

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [deploy]

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 4: Run integration tests
      - name: Run integration tests
        env:
          DATABASE_URL: postgres://test:test@localhost:5432/test_db?sslmode=disable
        run: go test -v ./integration_tests
