name: CI Pipeline

# Запускать при каждом пуше или pull request в ветку main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонировать репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установить Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3

      # Шаг 3: Кэшировать зависимости
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Шаг 4: Установить зависимости
      - name: Install dependencies
        run: go mod tidy

      # Шаг 5: Запустить тесты
      - name: Run tests
        run: go test -v ./...

      # Шаг 6: Сборка приложения
      - name: Build application
        run: go build -o bankapp main.go
